### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by tschoonj** [PieterTack/polycap#15]
This is the big one.

I suggest to use Doxygen for the C code and sphinx for the Python bindings.

I think it's best that Pieter does the former, while I do the latter, as well as the necessary changes to the build system.

Inspiration for the C code documentation can be found in [easyRNG](https://github.com/tschoonj/easyRNG), in the public headers [easy_rng.h](https://github.com/tschoonj/easyRNG/blob/master/src/easy_rng.h) and [easy_randist.h](https://github.com/tschoonj/easyRNG/blob/master/src/easy_randist.h).

**Comment by PieterTack** [comment]
Mainly Cython/Python docs
Installation docs

**Comment by PieterTack** [comment]
@tschoonj Hoi Tom, ik weet niet goed hoe hieraan te beginnen :( Ik keek eens naar die [Sphinx](https://www.sphinx-doc.org/en/master/) info, maar ik had iets verwacht waar ik in de code informatie geef bij de functies en dat een programma dan uitleest en in een mooie layout giet (zoals bij onze C code het geval is). Ik zie hiervan niet direct iets terug bij `Sphinx`?

**Comment by tschoonj** [comment]
Hey Pieter,

Anders gebruiken we geen sphinx, en schrijven we gewoon een extra pagina met de Python classes, en voegen we die dan toe aan de website. Een beetje zoals we nu al doen voor `Usage` etc.

**Comment by PieterTack** [comment]
Ja, dat zal voor mijn hoofd vast het gemakkelijkste zijn :P 
Thx for the input!

**Comment by PieterTack** [comment]
Sluiten we deze issue dan? Of zijn er nog delen docu te kort?
